<?php
/**
 * Adyen Payment Module
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category	Adyen
 * @package	Adyen_Payment
 * @copyright	Copyright (c) 2011 Adyen (http://www.adyen.com)
 * @license	http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
/**
 * @category   Payment Gateway
 * @package    Adyen_Payment
 * @author     Adyen
 * @property   Adyen B.V
 * @copyright  Copyright (c) 2014 Adyen BV (http://www.adyen.com)
 */
?>
<?php echo $this->htmlEscape($this->getMethod()->getTitle()) ?><br/>
<?php if ($_info = $this->getInfo()): ?>
    <?php if ($_info->getAdyenPspReference() == ''): ?>        
        <?php echo Mage::helper('adyen')->__('Payment has not been processed yet.') ?> <br/> 
    <?php else :?>
         <?php if($this->getMethod()->getConfigDataDemoMode()): ?>
                <?php echo Mage::helper('adyen')->__('Adyen PSP Reference: <a href="https://ca-test.adyen.com/ca/ca/accounts/showTx.shtml?pspReference=%s&txType=Payment" target="__blank">%s</a>', $this->htmlEscape($_info->getAdyenPspReference()), $this->htmlEscape($_info->getAdyenPspReference())) ?> <br/>
           <?php else : ?>
                <?php echo Mage::helper('adyen')->__('Adyen PSP Reference: <a href="https://ca-live.adyen.com/ca/ca/accounts/showTx.shtml?pspReference=%s&txType=Payment" target="__blank">%s</a>', $this->htmlEscape($_info->getAdyenPspReference()), $this->htmlEscape($_info->getAdyenPspReference())) ?> <br/>
            <?php endif; ?>
        <?php endif;?>
    <?php $paymentMethod = $_info->getCcType() ?>
    <?php if (!empty($paymentMethod)): ?>
        <?php echo $this->__('Payment Method: %s', $this->htmlEscape($paymentMethod)) ?><br/>
    <?php endif; ?>
    <?php if (strpos($_info->getCcType(), "ideal") !== false): ?>            
        <?php $bankData = $_info->getPoNumber(); ?>
        <?php if (!empty($bankData)) : ?>
            <?php
            $id = explode(DS, $bankData);
            $label = $id['1'];
            ?>
            <?php echo $this->__('Bank: %s', $this->htmlEscape($label)) ?><br/>
        <?php endif; ?>            
    <?php endif; ?>
            
    <!-- SOFORT -->
    <?php if($_info->getOwnerName() != null && $_info->getOwnerName() != ""): ?>
        <?php echo Mage::helper('adyen')->__('Payer Owner Name: %s', $this->htmlEscape($_info->getOwnerName())) ?> <br/>
    <?php endif; ?>
    <?php if($_info->getBankName() != null && $_info->getBankName() != ""): ?>
        <?php echo Mage::helper('adyen')->__('Payer Bank Name: %s', $this->htmlEscape($_info->getBankName())) ?> <br/>
    <?php endif; ?>
    <?php if($_info->getIban() != null && $_info->getIban() != ""): ?>
        <?php echo Mage::helper('adyen')->__('Payer IBAN: %s', $this->htmlEscape($_info->getIban())) ?> <br/>
    <?php endif; ?>
    <?php if($_info->getBic() != null && $_info->getBic() != ""): ?>
        <?php echo Mage::helper('adyen')->__('Payer BIC: %s', $this->htmlEscape($_info->getBic())) ?> <br/>
    <?php endif; ?>
    
    <!-- PAYPAL -->
    <?php if($_info->getPayerStatus() != null && $_info->getPayerStatus() != ""): ?>
        <?php echo Mage::helper('adyen')->__('Payer Status: %s', $this->htmlEscape($_info->getPayerStatus())) ?> <br/>
    <?php endif; ?>
    <?php if($_info->getPayerCountry() != null && $_info->getPayerCountry() != ""): ?>
        <?php echo Mage::helper('adyen')->__('Payer Country: %s', $this->htmlEscape($_info->getPayerCountry())) ?> <br/>
    <?php endif; ?>
    <?php if($_info->getProtectionEligibility() != null && $_info->getProtectionEligibility() != ""): ?>
        <?php echo Mage::helper('adyen')->__('Payer Protection Eligibility: %s', $this->htmlEscape($_info->getProtectionEligibility())) ?> <br/>
    <?php endif; ?>
    <?php if($_info->getPayerEmail() != null && $_info->getPayerEmail() != ""): ?>
        <?php echo Mage::helper('adyen')->__('Payer Email: %s', $this->htmlEscape($_info->getPayerEmail())) ?> <br/>
    <?php endif; ?>
    <?php if($_info->getPaypalEmail() != null && $_info->getPaypalEmail() != ""): ?>
        <?php echo Mage::helper('adyen')->__('Paypal Payer Email: %s', $this->htmlEscape($_info->getPaypalEmail())) ?> <br/>
    <?php endif; ?>
    <?php if($_info->getPaypalPayerId() != null && $_info->getPaypalPayerId() != ""): ?>
        <?php echo Mage::helper('adyen')->__('Paypal Payer Id: %s', $this->htmlEscape($_info->getPaypalPayerId())) ?> <br/>
    <?php endif; ?>
    <?php if($_info->getPaypalPayerResidenceCountry() != null && $_info->getPaypalPayerResidenceCountry() != ""): ?>
        <?php echo Mage::helper('adyen')->__('Paypal Payer Residence Country: %s', $this->htmlEscape($_info->getPaypalPayerResidenceCountry())) ?> <br/>
    <?php endif; ?>
        
    <!-- KLARNA -->
    <?php if($_info->getAdyenKlarnaNumber() != null && $_info->getAdyenKlarnaNumber() != ""): ?>
        <?php echo Mage::helper('adyen')->__('Klarna reservation number: %s', $this->htmlEscape($_info->getAdyenKlarnaNumber())) ?> <br/>
    <?php endif; ?>
    
    <!-- GENERAL -->    
    <?php if($this->htmlEscape($this->getInfo()->getAdyenRefusalReasonRaw()) != ""): ?>
        <?php echo Mage::helper('adyen')->__('Raw acquirer response: %s', $this->htmlEscape($this->getInfo()->getAdyenRefusalReasonRaw())) ?><br/>
    <?php endif; ?>
    <?php if($this->htmlEscape($this->getInfo()->getAdyenAuthCode()) != ""): ?>
        <?php echo Mage::helper('adyen')->__('Authorisation code: %s', $this->htmlEscape($this->getInfo()->getAdyenAuthCode())) ?><br/>
    <?php endif; ?>
    <?php if($this->htmlEscape($this->getInfo()->getAdyenAcquirerReference()) != ""): ?>
        <?php echo Mage::helper('adyen')->__('Acquirer reference: %s', $this->htmlEscape($this->getInfo()->getAdyenAcquirerReference())) ?><br/>
    <?php endif; ?>
<?php endif; ?>
